/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_readsense_app_control_ControlGate */

#ifndef _Included_com_readsense_app_control_ControlGate
#define _Included_com_readsense_app_control_ControlGate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_readsense_app_control_ControlGate
 * Method:    sendCmd
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_readsense_app_control_ControlGate_sendCmd
        (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
