/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobile_ReadFace_FaceAnalyze */

#ifndef _Included_cn_readsense_readbody_BodyAnalyze
#define _Included_cn_readsense_readbody_BodyAnalyze
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_cn_readsense_readbody_BodyAnalyze_nativeCreateObject2(
    JNIEnv *, jclass , jobject , jstring );

JNIEXPORT void JNICALL Java_cn_readsense_readbody_BodyAnalyze_nativeDestroyObject2(
    JNIEnv *, jclass );

JNIEXPORT jlong JNICALL Java_cn_readsense_readbody_BodyAnalyze_nativeBodyTrack2(
    JNIEnv *, jobject, jbyteArray, jint,jint, jint, jint,jobject);

JNIEXPORT void JNICALL Java_cn_readsense_readbody_BodyAnalyze_nativeBodyReset(
    JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
